#!/bin/sh

# These are the physical network devices
# eth0 Internal switch
# eth1 SFP2 'LAN'
# eth2 SFP1 'WAN'
#
# And on the switch there are 4 ports from SFP to power supply
# wan, lan1, lan2, lan3
#
# These are the wireless devices
# radio0 2.4GHz
# radio1 5GHz
# radio2 6GHz

set -eux
exec >> /root/uci-defaults.log 2>&1

# Clear existing configuration
uci delete network.lan
uci delete network.wan
uci delete network.wan6
while uci -q delete network.@device[0]; do :; done
uci delete dhcp.lan
uci delete dhcp.wan
while uci -q delete firewall.@zone[0]; do :; done
while uci -q delete firewall.@forwarding[0]; do :; done
while uci -q delete firewall.@rule[0]; do :; done

# External WAN and WAN6 over SFP1 using PPPoE and VLAN 7
uci set network.fiber_vlan=device
uci set network.fiber_vlan.type='8021q'
uci set network.fiber_vlan.ifname='eth2'
uci set network.fiber_vlan.vid='7'
uci set network.fiber_vlan.name='eth2.7'

uci set network.fiber_wan=interface
uci set network.fiber_wan.device='eth2.7'
uci set network.fiber_wan.proto='pppoe'
uci set network.fiber_wan.username='${PPPOE_USERNAME}'
uci set network.fiber_wan.password='${PPPOE_PASSWORD}'
uci add_list network.fiber_wan.dns='1.1.1.1'
uci add_list network.fiber_wan.dns='1.0.0.1'
uci set network.fiber_wan.peerdns='0'
uci set network.fiber_wan.ipv6='1'

uci set network.fiber_wan6=interface
uci set network.fiber_wan6.device='@fiber_wan'
uci set network.fiber_wan6.proto='dhcpv6'
uci add_list network.fiber_wan6.dns='2606:4700:4700::1111'
uci add_list network.fiber_wan6.dns='2606:4700:4700::1001'
uci set network.fiber_wan6.peerdns='0'

# External WAN and WAN6 over USB tethering
uci set network.tethering_wan=interface
uci set network.tethering_wan.device='usb0'
uci set network.tethering_wan.proto='dhcp'
uci add_list network.tethering_wan.dns='1.1.1.1'
uci add_list network.tethering_wan.dns='1.0.0.1'
uci set network.tethering_wan.peerdns='0'

uci set network.tethering_wan6=interface
uci set network.tethering_wan6.device='usb0'
uci set network.tethering_wan6.proto='dhcpv6'
uci add_list network.tethering_wan6.dns='2606:4700:4700::1111'
uci add_list network.tethering_wan6.dns='2606:4700:4700::1001'
uci set network.tethering_wan6.reqaddress='try'
uci set network.tethering_wan6.reqprefix='auto'
uci set network.tethering_wan6.peerdns='0'

# WAN zone
uci set firewall.wan='zone'
uci set firewall.wan.name='wan'
uci set firewall.wan.network='fiber_wan fiber_wan6 tethering_wan tethering_wan6'
uci set firewall.wan.input='REJECT'
uci set firewall.wan.output='ACCEPT'
uci set firewall.wan.forward='REJECT'
uci set firewall.wan.masq='1'
uci set firewall.wan.mtu_fix='1'

# Access to the SFP module's web interface
uci set network.fiber_ont=interface
uci set network.fiber_ont.device='eth2'
uci set network.fiber_ont.proto='static'
uci set network.fiber_ont.ipaddr='192.168.1.2'
uci set network.fiber_ont.netmask='255.255.255.0'

echo "192.168.1.1 ont" >> /etc/hosts

uci set firewall.ont='zone'
uci set firewall.ont.name='ont'
uci set firewall.ont.network='fiber_ont'
uci set firewall.ont.input='REJECT'
uci set firewall.ont.output='ACCEPT'
uci set firewall.ont.forward='REJECT'

# Enable flow offloading to improve performance
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'

### Firewall rules ###
# Allow DHCP renewal for IPv4
uci set firewall.allow_dhcp_renew='rule'
uci set firewall.allow_dhcp_renew.name='Allow-DHCP-Renew'
uci set firewall.allow_dhcp_renew.src='wan'
uci set firewall.allow_dhcp_renew.proto='udp'
uci set firewall.allow_dhcp_renew.dest_port='68'
uci set firewall.allow_dhcp_renew.family='ipv4'
uci set firewall.allow_dhcp_renew.target='ACCEPT'

# Allow DHCP renewal for IPv6
uci set firewall.allow_dhcpv6='rule'
uci set firewall.allow_dhcpv6.name='Allow-DHCPv6'
uci set firewall.allow_dhcpv6.src='wan'
uci set firewall.allow_dhcpv6.proto='udp'
uci set firewall.allow_dhcpv6.dest_port='546'
uci set firewall.allow_dhcpv6.family='ipv6'
uci set firewall.allow_dhcpv6.target='ACCEPT'

# Allow IPv4 ping
uci set firewall.allow_ping='rule'
uci set firewall.allow_ping.name='Allow-Ping'
uci set firewall.allow_ping.src='wan'
uci set firewall.allow_ping.proto='icmp'
uci add_list firewall.allow_ping.icmp_type='echo-request'
uci set firewall.allow_ping.family='ipv4'
uci set firewall.allow_ping.target='ACCEPT'
uci set firewall.allow_ping.limit='10/sec'

# Allow ICMPv6 input (essential for IPv6 functionality)
uci set firewall.allow_icmpv6_input='rule'
uci set firewall.allow_icmpv6_input.name='Allow-ICMPv6-Input'
uci set firewall.allow_icmpv6_input.src='wan'
uci set firewall.allow_icmpv6_input.proto='icmp'
uci add_list firewall.allow_icmpv6_input.icmp_type='echo-request'
uci add_list firewall.allow_icmpv6_input.icmp_type='echo-reply'
uci add_list firewall.allow_icmpv6_input.icmp_type='destination-unreachable'
uci add_list firewall.allow_icmpv6_input.icmp_type='packet-too-big'
uci add_list firewall.allow_icmpv6_input.icmp_type='time-exceeded'
uci add_list firewall.allow_icmpv6_input.icmp_type='bad-header'
uci add_list firewall.allow_icmpv6_input.icmp_type='unknown-header-type'
uci add_list firewall.allow_icmpv6_input.icmp_type='router-solicitation'
uci add_list firewall.allow_icmpv6_input.icmp_type='neighbour-solicitation'
uci add_list firewall.allow_icmpv6_input.icmp_type='router-advertisement'
uci add_list firewall.allow_icmpv6_input.icmp_type='neighbour-advertisement'
uci set firewall.allow_icmpv6_input.limit='1000/sec'
uci set firewall.allow_icmpv6_input.family='ipv6'
uci set firewall.allow_icmpv6_input.target='ACCEPT'

# Allow ICMPv6 forward (essential for IPv6 functionality)
uci set firewall.allow_icmpv6_forward='rule'
uci set firewall.allow_icmpv6_forward.name='Allow-ICMPv6-Forward'
uci set firewall.allow_icmpv6_forward.src='wan'
uci set firewall.allow_icmpv6_forward.dest='*'
uci set firewall.allow_icmpv6_forward.proto='icmp'
uci add_list firewall.allow_icmpv6_forward.icmp_type='echo-request'
uci add_list firewall.allow_icmpv6_forward.icmp_type='echo-reply'
uci add_list firewall.allow_icmpv6_forward.icmp_type='destination-unreachable'
uci add_list firewall.allow_icmpv6_forward.icmp_type='packet-too-big'
uci add_list firewall.allow_icmpv6_forward.icmp_type='time-exceeded'
uci add_list firewall.allow_icmpv6_forward.icmp_type='bad-header'
uci add_list firewall.allow_icmpv6_forward.icmp_type='unknown-header-type'
uci set firewall.allow_icmpv6_forward.limit='1000/sec'
uci set firewall.allow_icmpv6_forward.family='ipv6'
uci set firewall.allow_icmpv6_forward.target='ACCEPT'

# Allow IGMP for IPv4 multicast (like IPTV)
uci set firewall.allow_igmp='rule'
uci set firewall.allow_igmp.name='Allow-IGMP'
uci set firewall.allow_igmp.src='wan'
uci set firewall.allow_igmp.proto='igmp'
uci set firewall.allow_igmp.family='ipv4'
uci set firewall.allow_igmp.target='ACCEPT'

# Allow MLD for IPv6 multicast (like IPTV)
uci set firewall.allow_mld='rule'
uci set firewall.allow_mld.name='Allow-MLD'
uci set firewall.allow_mld.src='wan'
uci set firewall.allow_mld.proto='icmp'
uci set firewall.allow_mld.src_ip='fe80::/10'
uci add_list firewall.allow_mld.icmp_type='multicast-listener-query'
uci add_list firewall.allow_mld.icmp_type='multicast-listener-report'
uci add_list firewall.allow_mld.icmp_type='multicast-listener-done'
uci add_list firewall.allow_mld.icmp_type='v2-multicast-listener-report'
uci set firewall.allow_mld.family='ipv6'
uci set firewall.allow_mld.target='ACCEPT'

### Wireless configuration ###
uci delete wireless.default_radio0
uci delete wireless.default_radio1
uci delete wireless.default_radio2

# 2.4Ghz, Wifi 7, 20Mhz
uci rename wireless.radio0=radio2g
uci set wireless.radio2g.country='DE'
uci set wireless.radio2g.channel='auto'
uci set wireless.radio2g.htmode='EHT20'
uci set wireless.radio2g.disabled='0'

# 5Ghz, Wifi 7, 40Mhz
# Restrict to UNII-1 (36-64) & UNII-2 Extended (100-136) for legacy device support
# Excluding channel 140 to avoid selecting channel 144
uci rename wireless.radio1=radio5g
uci set wireless.radio5g.country='DE'
uci set wireless.radio5g.channels='36-64 100-136'
uci set wireless.radio5g.channel='auto'
uci set wireless.radio5g.htmode='EHT40'
uci set wireless.radio5g.disabled='0'

# 6Ghz, Wifi 7, 80Mhz
uci rename wireless.radio2=radio6g
uci set wireless.radio6g.country='DE'
uci set wireless.radio6g.channel='auto'
uci set wireless.radio6g.htmode='EHT80'
uci set wireless.radio6g.disabled='0'

uci commit
