#!/bin/sh

set -eux
exec >> /root/uci-defaults.log 2>&1

# IoT LAN (wired and wireless)
uci set network.iot_bridge=device
uci set network.iot_bridge.name='br-iot'
uci set network.iot_bridge.type='bridge'
uci set network.iot_bridge.ports='wan'

uci set network.iot_lan=interface
uci set network.iot_lan.device='br-iot'
uci set network.iot_lan.proto='static'
uci set network.iot_lan.ipaddr='10.10.30.1'
uci set network.iot_lan.netmask='255.255.255.0'

uci set wireless.iot_2g=wifi-iface
uci set wireless.iot_2g.device='radio2g'
uci set wireless.iot_2g.mode='ap'
uci set wireless.iot_2g.ssid='${IOT_SSID}'
uci set wireless.iot_2g.encryption='psk2'
uci set wireless.iot_2g.key='${IOT_PASSWORD}'
uci set wireless.iot_2g.network='iot_lan'
uci set wireless.iot_2g.isolate='1'
uci set wireless.iot_2g.ocv='0'

# DHCP server with IPv4 only
# DHCP with hard-coded macs or at least name:mac mapping?
uci set dhcp.iot=dhcp
uci set dhcp.iot.interface='iot_lan'
uci set dhcp.iot.start='100'
uci set dhcp.iot.limit='50'
uci set dhcp.iot.leasetime='24h'
uci set dhcp.iot.dhcpv4='server'

# Firewall zone with limited access
uci set firewall.iot='zone'
uci set firewall.iot.name='iot'
uci set firewall.iot.network='iot_lan'
uci set firewall.iot.input='REJECT'
uci set firewall.iot.output='ACCEPT'
uci set firewall.iot.forward='REJECT'

# Allow traffic to the world
uci set firewall.iot_wan='forwarding'
uci set firewall.iot_wan.src='iot'
uci set firewall.iot_wan.dest='wan'

# Allow DNS traffic from IoT to router
uci set firewall.iot_dns='rule'
uci set firewall.iot_dns.name='Allow-DNS-IoT'
uci set firewall.iot_dns.src='iot'
uci set firewall.iot_dns.dest_port='53'
uci set firewall.iot_dns.proto='tcp udp'
uci set firewall.iot_dns.target='ACCEPT'

# Allow DHCP traffic from IoT to router
uci set firewall.iot_dhcp='rule'
uci set firewall.iot_dhcp.name='Allow-DHCP-IoT'
uci set firewall.iot_dhcp.src='iot'
uci set firewall.iot_dhcp.dest_port='67-68'
uci set firewall.iot_dhcp.proto='udp'
uci set firewall.iot_dhcp.family='ipv4'
uci set firewall.iot_dhcp.target='ACCEPT'

uci commit
