#!/bin/sh

set -eux
exec >> /root/uci-defaults.log 2>&1

uci delete stubby.global.trigger
uci add_list stubby.global.trigger='fiber_wan'
uci add_list stubby.global.trigger='tethering_wan'

uci set stubby.global.dnssec_return_status='1'

# Remove default resolvers and replace with Cloudflare DNS
while uci -q delete stubby.@resolver[0]; do :; done

uci add stubby resolver
uci set stubby.@resolver[-1].address='1.1.1.1'
uci set stubby.@resolver[-1].tls_auth_name='cloudflare-dns.com'

uci add stubby resolver
uci set stubby.@resolver[-1].address='1.0.0.1'
uci set stubby.@resolver[-1].tls_auth_name='cloudflare-dns.com'

uci add stubby resolver
uci set stubby.@resolver[-1].address='2606:4700:4700::1111'
uci set stubby.@resolver[-1].tls_auth_name='cloudflare-dns.com'

uci add stubby resolver
uci set stubby.@resolver[-1].address='2606:4700:4700::1001'
uci set stubby.@resolver[-1].tls_auth_name='cloudflare-dns.com'

uci commit stubby
