#!/bin/sh

set -eux
exec >> /root/uci-defaults.log 2>&1
echo "Running 921-dnsmasq"

uci set dhcp.@dnsmasq[0].local='/${DOMAIN}/'
uci set dhcp.@dnsmasq[0].domain='${DOMAIN}'

# Listen only on the internal interfaces
uci -q delete dhcp.@dnsmasq[0].interface || true
uci -q delete dhcp.@dnsmasq[0].notinterface || true

uci add_list dhcp.@dnsmasq[0].interface='private_lan'
uci add_list dhcp.@dnsmasq[0].interface='guest_lan'
uci add_list dhcp.@dnsmasq[0].interface='iot_lan'
uci add_list dhcp.@dnsmasq[0].interface='container_lan'
uci add_list dhcp.@dnsmasq[0].interface='vpn'

# Enable DNS security via local stubby instance
uci set dhcp.@dnsmasq[0].noresolv='1'
uci set dhcp.@dnsmasq[0].proxydnssec='1'

uci -q delete dhcp.@dnsmasq[0].server || true
uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5453'

# Prevent stubby deadlocking dnsmasq on boot when time is not synced
uci add_list dhcp.@dnsmasq[0].server='/pool.ntp.org/1.1.1.1'

uci commit dhcp
